spring:
  application:
    name: microservice-c
  zipkin:
    sender:
      type: kafka
  sleuth:
    enabled: true
    sampler:
      percentage: 1
  kafka:
    bootstrap-servers:
    - localhost:9092,localhost:9093,localhost:9094
server:
  port: 8883
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/